example:
  property: "Dev from git"

spring:
  datasource:
    url: jdbc:mysql://database:3306/licensing_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
