example:
  property: "Default from Git"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/licensing
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

